/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DataEngineeringRouteImport } from './routes/data-engineering'
import { Route as DataAnalyticsRouteImport } from './routes/data-analytics'
import { Route as IndexRouteImport } from './routes/index'

const DataEngineeringRoute = DataEngineeringRouteImport.update({
  id: '/data-engineering',
  path: '/data-engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const DataAnalyticsRoute = DataAnalyticsRouteImport.update({
  id: '/data-analytics',
  path: '/data-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-analytics': typeof DataAnalyticsRoute
  '/data-engineering': typeof DataEngineeringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-analytics': typeof DataAnalyticsRoute
  '/data-engineering': typeof DataEngineeringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-analytics': typeof DataAnalyticsRoute
  '/data-engineering': typeof DataEngineeringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data-analytics' | '/data-engineering'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data-analytics' | '/data-engineering'
  id: '__root__' | '/' | '/data-analytics' | '/data-engineering'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataAnalyticsRoute: typeof DataAnalyticsRoute
  DataEngineeringRoute: typeof DataEngineeringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/data-engineering': {
      id: '/data-engineering'
      path: '/data-engineering'
      fullPath: '/data-engineering'
      preLoaderRoute: typeof DataEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-analytics': {
      id: '/data-analytics'
      path: '/data-analytics'
      fullPath: '/data-analytics'
      preLoaderRoute: typeof DataAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataAnalyticsRoute: DataAnalyticsRoute,
  DataEngineeringRoute: DataEngineeringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
